put all the neat little commands into the functions they belong in

diff --git a/.zrc/functions b/.zrc/functions
--- a/.zrc/functions
+++ b/.zrc/functions
@@ -1,5 +1,78 @@
 # DEFINE FUNCTIONS
 
+# repeats until no errors happen
+function cycle {
+   $@
+
+   while [ $? -ne 0 ]
+   do
+      echo "command: $1 exited with code 1 [ERROR]"
+      echo "waiting 5 seconds for User Interrupt until recursion"
+      sleep 5s
+   done
+}
+
+function mapArg () {
+   while read -r line; do
+      $@ "$line"
+   done
+}
+
+function map () {
+   while read -r line; do
+      echo "$line" | $@
+   done
+}
+
+# hardlinks a list of files into a target directory
+# stdin	 list of files to link
+# $1	 target directory
+function linkFilesTo () {
+   while read -r file; do
+      ln "$file" "$1"
+   done
+}
+
+function prependFilesWithPWD () {
+   while read -r file; do
+      echo "$PWD/$file"
+   done
+}
+
+function prependItemsWith () {
+   while read -r line; do
+      echo "$@$line"
+   done
+}
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 # search function, that combines content search via ag and file search via fd, and lets you select via fzf
 search(){
 	# if $2 is 'a' or 'all', search hidden files and gitignore files (ag: -a means don't exclude based on extension)
